local symbols = {
  left_semicircle = "",
  right_semicircle = "",
  left_upside_down_right_triangle = " ",
  right_upside_down_right_triangle = " ",
  left_arrow = "",
  right_arrow = "",
  left_arrow_separator = "",
  generic_separator = "|",
  folder = "",
  linux_logo = "",
  darwin_logo = "",
  windows_logo = "",
  unknown_logo = " ",
  laptop = " ",
  peacock = "🦚",
  ln = "",
  lsp_warnings_symbol = " ",
  lsp_error_symbol = " ",
  diff_add_symbol = "+",
  diff_mod_symbol = "~",
  diff_removed_symbol = "-",
}

return symbols
